name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to ec2
    runs-on: ubuntu-latest

    steps:
      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@v1
        id: ssm
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: i-0b3933362461dc47b

          working-directory: /home/ubuntu/subcloud-strapi
          command: git pull && npm ci && npm run build && pm2 start ecosystem.config.js

      - name: Get the outputs
        run: echo "The Command id is ${{ steps.ssm.outputs.command-id }}"
